# TCL File Generated by Component Editor 11.0
# Thu Jun 30 12:46:13 CEST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | i2c_master_avalon "i2c_master_avalon" v1.0
# | null 2011.06.30.12:46:13
# | 
# | 
# | /home/git/80048_wpe_fpga_firmware/ip/i2c_master_avalon/i2c_master_avalon.vhd
# | 
# |    ./i2c_master_avalon.vhd syn, sim
# |    ./i2c_master_bit_ctrl.vhd syn, sim
# |    ./i2c_master_byte_ctrl.vhd syn, sim
# |    ./i2c_master_top.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module i2c_master_avalon
# | 
set_module_property NAME i2c_master_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Serial"
set_module_property DISPLAY_NAME i2c_master_avalon
set_module_property TOP_LEVEL_HDL_FILE i2c_master_avalon.vhd
set_module_property TOP_LEVEL_HDL_MODULE i2c_master_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file i2c_master_avalon.vhd {SYNTHESIS SIMULATION}
add_file i2c_master_bit_ctrl.vhd {SYNTHESIS SIMULATION}
add_file i2c_master_byte_ctrl.vhd {SYNTHESIS SIMULATION}
add_file i2c_master_top.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 wrdata writedata Input 8
add_interface_port avalon_slave_0 rddata readdata Output 8
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 waitrequest_n waitrequest_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end scl_pad_i export Input 1
add_interface_port conduit_end scl_pad_o export Output 1
add_interface_port conduit_end scl_padoen_o export Output 1
add_interface_port conduit_end sda_pad_i export Input 1
add_interface_port conduit_end sda_pad_o export Output 1
add_interface_port conduit_end sda_padoen_o export Output 1
# | 
# +-----------------------------------
